version: '2'

services:

  reward:
    image: reward:1.0.8
    networks:
      - oc
    ports:
      - "9001:9001"

  gps-util:
    image: gps-util:1.0.8
    networks:
      - oc
    ports:
      - "9002:9002"

  trip-pricer:
    image: trip-pricer:1.0.8
    networks:
      - oc
    ports:
      - "9003:9003"

  tour-guide:
    image: tour-guide:1.0.8
    ports:
      - "8080:8080"
    networks:
      - oc
    depends_on:
      - reward
      - gps-util
      - trip-pricer

networks:
  oc:
    driver: bridge